name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"  # or the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev

    - name: Install package in editable mode
      run: pip install -e .

    - name: Run pytest
      run: pytest
